OPTION(MsMpi_USE_86x_ARCH "Enable this if you compile for x86 (32 bit) system" OFF)
if(MsMpi_USE_86x_ARCH)
    set(MsMpi_SYSTEM_ARCH "x86")
else()
    set(MsMpi_SYSTEM_ARCH "x64")
endif()
set(MsMpi_DIR "D:\\libs\\Microsoft SDKs\\MPI")
set(MsMpi_INCLUDE_DIRS "${MsMpi_ROOT_DIR}\\Include" "${MsMpi_ROOT_DIR}\\Include\\${MsMpi_SYSTEM_ARCH}")
set(MsMpi_LIBRARY_DIRS "${MPI_root}\\Lib\\${MsMpi_SYSTEM_ARCH}")
set(MsMpi_LIBRARY msmpi)
